using MPP_5.DIUtils;

namespace Tests.HelperClasses
{
    public class HelperClassForCommon : TestInterface
    {

        public readonly string thisShouldNotBeEmpty = "";
        public readonly string thisShouldBeEmpty = "";
        public readonly string autoGenerated = "";
        public readonly NestedInterface nested;

        public HelperClassForCommon() { 
            
        }

        [DependencyConstructor]
        public HelperClassForCommon([DependencyKey("Impl2")]NestedInterface nested, 
            string parameter, string str)
        {
            this.nested = nested;
            this.autoGenerated = str;
            thisShouldNotBeEmpty = parameter;
        }
    }

    public interface TestInterface { }

    public class Impl1 : NestedInterface {
        [DependencyConstructor]
        public Impl1 () { }
    }
    public class Impl2 : NestedInterface {
        [DependencyConstructor]
        public Impl2() { }
    }

    public interface NestedInterface { }

    public interface DoubleNestedInterface { }

    public class Impl3 : DoubleNestedInterface
    {
        [DependencyConstructor]
        public Impl3() { }
    }

}
